# Generated by Django 4.2.5 on 2023-09-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inheritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_tax_id', models.CharField(max_length=100)),
                ('created_when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InheritorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping_key', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('inheritor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wills.inheritor')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('distributed', models.BooleanField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wills.asset')),
                ('inheritor_group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wills.inheritorgroup')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='will_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wills.will'),
        ),
    ]
