# Generated by Django 4.2.5 on 2023-09-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='will_id',
            new_name='will',
        ),
        migrations.RenameField(
            model_name='inheritorgroup',
            old_name='inheritor_id',
            new_name='inheritors',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wills.asset'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='inheritor_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wills.inheritorgroup'),
        ),
    ]
