# Generated by Django 4.2.5 on 2023-09-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0002_rename_will_id_asset_will_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='asset_id',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='inheritor_group_id',
            new_name='inheritor_group',
        ),
    ]
