# Generated by Django 4.2.5 on 2023-10-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0003_rename_asset_id_distribution_asset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inheritorgroup',
            old_name='inheritors',
            new_name='inheritor',
        ),
        migrations.AlterField(
            model_name='asset',
            name='will',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wills.will'),
        ),
    ]
